name: Build Signed APK

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # UPDATED: Bumped to 3.24.3 to support Dart 3.5.0+ (required by flutter_lints 5.0.0)
          flutter-version: '3.24.3'

      # 1. Decode the Keystore File
      - name: Decode Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/release-key.jks

      # 2. Create key.properties
      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=../release-key.jks" >> android/key.properties

      # 3. Create .env file
      - name: Create .env file
        run: |
          echo "deezerClientId = '${{ secrets.DEEZER_CLIENT_ID }}'" > lib/.env
          echo "deezerClientSecret = '${{ secrets.DEEZER_CLIENT_SECRET }}'" >> lib/.env
          echo "lastFmApiKey = '${{ secrets.LASTFM_API_KEY }}'" >> lib/.env
          echo "lastFmApiSecret = '${{ secrets.LASTFM_API_SECRET }}'" >> lib/.env

      - name: Get Dependencies
        run: flutter pub get

      # 4. Run Build Runner
      - name: Run Build Runner
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build Signed APK
        run: flutter build apk --split-per-abi --release

      # 5. Upload Artifacts
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apks
          path: build/app/outputs/flutter-apk/*.apk
